<a href="https://colab.research.google.com/github/19PA1A0288/AI-LAB-EXPERIMENTS/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Experiment 1 Numpy¶

#Different ways to create Numpy arrays¶

##i)Creat a numpy array using list

In [18]:
import numpy as np 
p=np.array([1,8,9])
print(p)

[1 8 9]


#ii)Add,Remove,Modify array elements add

###Add

In [19]:
f=np.array([4,1,9])
q=np.append(f,[3,6,8])
print(q)

[4 1 9 3 6 8]


###Remove

In [20]:
c=np.delete(f,2)
print(c)

[4 1]


###Modify

In [21]:
c[c>3]=-1
print(c)

[-1  1]


##iii)Arthemetic operations on Numpy array

In [22]:
 import numpy as np 
l=np.random.random((5,5))
m=np.random.random((5,5))
num_sum=np.add(l,m)
num_diff=np.subtract(l,m)
num_prod=np.multiply(l,m)
num_quo=np.divide(l,m)
num_mod=np.mod(l,m)
num_pow=np.power(l,m)
print(num_sum)
print(num_diff)
print(num_prod)
print(num_quo)
print(num_mod)
print(num_pow)

[[0.21229076 1.82778727 0.88424269 0.80711732 1.43681579]
 [1.64614183 1.06064271 1.06709268 0.90465738 1.55189899]
 [0.62562027 1.38665779 0.9213102  1.34764013 0.91596994]
 [0.49186229 1.19699085 1.11989947 1.39097104 1.22683674]
 [0.32202609 1.47931721 1.02994379 0.63327051 1.32609935]]
[[ 0.12439647 -0.0018693  -0.03000504  0.06614575  0.46557716]
 [-0.11734585 -0.24117437  0.6518452   0.45116173 -0.15590738]
 [-0.24645537  0.33495498 -0.59194973 -0.04490445  0.57182921]
 [-0.31962253  0.43934543  0.18445659  0.22665541  0.28029788]
 [ 0.02849792 -0.22644826 -0.38241976  0.17078526  0.00238358]]
[[0.00739822 0.8352007  0.19524621 0.16176578 0.46191938]
 [0.67400322 0.26669947 0.17844616 0.15371452 0.59602084]
 [0.08266512 0.45265624 0.124602   0.45352938 0.12800307]
 [0.03494249 0.30994067 0.30503765 0.47085694 0.35664037]
 [0.02572217 0.53427515 0.22863484 0.09296598 0.43963345]]
[[3.83059267 0.99795666 0.93436124 1.1785379  1.95872867]
 [0.86691617 0.62948041 4.1395504  2.9897069

##iv)Slicing and Iterating of numpy array

###Slicing

In [23]:
import numpy as np 
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:6])

[2 3 4 5 6]


###Iterating

In [24]:
for x in arr:
  print(x)

1
2
3
4
5
6
7


##v)Matrix operations on Numpy arrays

In [25]:
import numpy as np 
s=np.array([[1,2],[3,4]])
t=np.array([[5,6],[7,8]])
print(np.add(s,t))
print(np.subtract(s,t))
print(np.divide(s,t))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
