<a href="https://colab.research.google.com/github/19PA1A0288/AI-LAB-EXPERIMENTS/blob/master/Welcome_To_Colaboratory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 # Experiment 1 Numpy

## Different ways to create Numpy arrays¶

### i)Creat a numpy array using list¶

In [38]:
import numpy as np 
p=np.array([1,8,9])
print(p)

[1 8 9]


### ii)Add,Remove,Modify array elements add

Add

In [41]:
 
f=np.array([4,1,9])
q=np.append(f,[3,6,8])
print(q)

[4 1 9 3 6 8]


Remove

In [42]:
c=np.delete(f,2)
print(c)

[4 1]


Modify

In [45]:
c[c>3]=-1
print(c)

[-1  1]


### iii)Arthemetic operations on Numpy array

In [48]:
 
import numpy as np 
l=np.random.random((5,5))
m=np.random.random((5,5))
num_sum=np.add(l,m)
num_diff=np.subtract(l,m)
num_prod=np.multiply(l,m)
num_quo=np.divide(l,m)
num_mod=np.mod(l,m)
num_pow=np.power(l,m)
print(num_sum)
print(num_diff)
print(num_prod)
print(num_quo)
print(num_mod)
print(num_pow)

[[0.24931574 1.30668997 0.8857726  1.40421563 1.85851139]
 [1.6070391  0.43707785 1.17982221 0.66377911 1.41797305]
 [0.52550664 1.20032795 0.58124642 1.36243021 1.6650428 ]
 [1.30830665 0.488208   1.16616608 0.93221128 1.29514863]
 [0.75340479 1.26321303 0.70384013 1.18035837 1.46957389]]
[[ 0.20295019  0.23839816 -0.74666802 -0.06827076 -0.13149656]
 [-0.05204021  0.20268551  0.80310083  0.484669    0.31364063]
 [ 0.51140535 -0.2177241   0.50555157 -0.29751465  0.05126193]
 [-0.23177315 -0.44071185  0.32126793 -0.84231984 -0.18197224]
 [-0.44554217 -0.64923741 -0.00776736  0.0460229   0.07576718]]
[[0.00524239 0.41265125 0.05676999 0.49179016 0.85919331]
 [0.64496662 0.03748891 0.18675238 0.05142467 0.47806928]
 [0.00365545 0.34834585 0.02056625 0.44192528 0.69243494]
 [0.41448687 0.01103003 0.31418256 0.03987879 0.41107402]
 [0.09227774 0.29354948 0.12383265 0.34778195 0.53847669]]
[[9.75435321e+00 1.44631655e+00 8.52126469e-02 9.07271449e-01
  8.67843182e-01]
 [9.37266159e-01 2.729

### iv)Slicing and Iterating of numpy array¶

Slicing

In [49]:
 
import numpy as np 
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:6])

[2 3 4 5 6]


 Iterating

In [50]:
 
for x in arr:
  print(x)

1
2
3
4
5
6
7


 ### v)Matrix operations on Numpy arrays

In [55]:
 
import numpy as np 
s=np.array([[1,2],[3,4]])
t=np.array([[5,6],[7,8]])
print(np.add(s,t))
print(np.subtract(s,t))
print(np.divide(s,t))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
