<a href="https://colab.research.google.com/github/19PA1A0288/AI-LAB-EXPERIMENTS/blob/master/Welcome_To_Colaboratory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Experiment 1 Numpy

##Different ways to create Numpy arrays

###i)Creat a numpy array using list

In [4]:
import numpy as np 
p=np.array([1,8,9])
print(p)

[1 8 9]


###ii)Add,Remove,Modify array elements add

Add

In [6]:
 
f=np.array([4,1,9])
q=np.append(f,[3,6,8])
print(q)

[4 1 9 3 6 8]


Remove

In [7]:
 c=np.delete(f,2)
print(c)

[4 1]


Modify

In [8]:
 c[c>3]=-1
print(c)

[-1  1]


##iii)Arthemetic operations on Numpy array

In [9]:
 import numpy as np 
l=np.random.random((5,5))
m=np.random.random((5,5))
num_sum=np.add(l,m)
num_diff=np.subtract(l,m)
num_prod=np.multiply(l,m)
num_quo=np.divide(l,m)
num_mod=np.mod(l,m)
num_pow=np.power(l,m)
print(num_sum)
print(num_diff)
print(num_prod)
print(num_quo)
print(num_mod)
print(num_pow)

[[1.26724792 1.67381602 0.89940625 1.04188606 1.60713097]
 [1.59389907 1.20094956 1.06121806 1.70377503 0.56321582]
 [1.23840788 1.57512636 1.47711518 1.6511322  1.22617251]
 [1.40087023 0.89881155 1.06038384 1.30755685 1.62961488]
 [1.42023679 1.06249974 1.54675681 0.94704157 0.87218825]]
[[ 0.58207074  0.29358837 -0.48454518 -0.25359485 -0.14225077]
 [-0.06676378  0.01121298 -0.66268887  0.20318873  0.10849442]
 [ 0.74362893 -0.35805095 -0.14312829  0.14957279 -0.46469783]
 [-0.39578355 -0.79015916 -0.33408844 -0.47670288 -0.35527713]
 [-0.19568237  0.20864899 -0.32869339  0.60819953  0.0882177 ]]
[[0.31677774 0.67886649 0.14353689 0.25530405 0.64065867]
 [0.63401421 0.36053853 0.17175681 0.71539093 0.07636025]
 [0.24516752 0.58820564 0.54034589 0.67596638 0.32188874]
 [0.4514482  0.04587767 0.2531997  0.37061482 0.6323557 ]
 [0.49469524 0.27134283 0.57110432 0.13174527 0.18823249]]
[[2.69903717 1.42542021 0.29976563 0.60849311 0.83737023]
 [0.91959382 1.01884951 0.23117791 1.2708124

###iv)Slicing and Iterating of numpy array

slicing

In [10]:
 import numpy as np 
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:6])

[2 3 4 5 6]


Iterating

In [11]:
 for x in arr:
  print(x)

1
2
3
4
5
6
7


###v)Matrix operations on Numpy arrays

In [12]:
 import numpy as np 
s=np.array([[1,2],[3,4]])
t=np.array([[5,6],[7,8]])
print(np.add(s,t))
print(np.subtract(s,t))
print(np.divide(s,t))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
